### ISSUE TITLE
Durable Message config

### ISSUE THREAD

**Issue by noniagriconomie** [swarrot/SwarrotBundle#102]
Hi,

We begin to use your bundle and the lib behind, it works well

I have 2 questions about our first implementation:

- to have a durable message, we need to add some properties in the message, do you confirm this behavior?

```php
            $message = new Message(json_encode([
                'channel' => SlackWebHookApi::CHANNEL_TECH_LOG,
                'text' => 'RabbitMq'.$i
            ]), ['delivery_mode' => 2]); // AMQP_DURABLE
            $messagePublisher->publish('slack_publisher', $message);
```

If i did not set the ['delivery_mode' => 2], if we publish message and restart the rabbitmq server, message is lost (queue empty)

- do you confirm that the ack processor is kind of mandatory, because if not set, the message is never removed from the queue? (so this https://github.com/swarrot/SwarrotBundle/issues/100 could be a very good idea)

Many thanks :)

**Comment by odolbeau** [comment]
Hi @noniagriconomie.

Regarding the first question, it's not mandatory. If your queues are explicitly created with the correct flag, you don't need to add this information in all message headers you sent.

For the second question, it's kind of mandatory in your case as you're using durable messages. When you don't use this option, you don't need to ack or nack any message when consuming them.

**Comment by noniagriconomie** [comment]
hey @odolbeau 

thank you for fast answer
Ok I understood, i will review my code/config then

issue closed :)
