### ISSUE TITLE
Upgrade swarrot/swarrot on dependancies?

### ISSUE THREAD

**Issue by metfan** [swarrot/SwarrotBundle#108]
Hello, 

Do you planned to upgrade swarrot/swarrot dependancy, the bundle is still on 2.2x branche.

Thank you

**Comment by odolbeau** [comment]
I don't have a lot of time right now but this should be done yes.
I'll try to handle this in the coming days if I have enough time...

**Comment by stof** [comment]
@odolbeau what are the BC breaks of swarrot 3.0 ?

**Comment by odolbeau** [comment]
Nothing. We bump PHP minimum version to 7.1. We could have done a minor release instead of a major one as suggested by @Taluu but I was afk during a couple of weeks and didn't correct my PR. :/

**Comment by stof** [comment]
OK, then it is just a matter of allowing both 2.x and 3.x in the bundle constraint

**Comment by olaurendeau** [comment]
So what about the next bundle version including the bump ? v2.0 as the lib ? v1.5.0 ? v1.4.3 ?

**Comment by mkingbe** [comment]
any news ?

**Comment by odolbeau** [comment]
@mkingbe SwarrotBundle v1.5.0 should do the job. :)
