### ISSUE TITLE
impossible to use an environment variable to define port number

### ISSUE THREAD

**Issue by lunika** [swarrot/SwarrotBundle#111]
Hello,

I need to use environment variable to define my rabbit configuration but it's not possible for the port number. In the dependency injection configuration an `integerNode` (https://github.com/swarrot/SwarrotBundle/blob/master/DependencyInjection/Configuration.php#L118) is used and by design an environment variable is a string.

Should be possible to accept a scalarNode and then normalize it as an integer ?

Thanks

**Comment by odolbeau** [comment]
It should now be OK thanks to this improvement:
https://symfony.com/blog/new-in-symfony-3-4-advanced-environment-variables

Feel free to open this issue again if you still have the problem.
