### ISSUE TITLE
Unable to manage heartbeats with PECL provider

### ISSUE THREAD

**Issue by dorianyah** [swarrot/SwarrotBundle#146]
Hi,

**Here is our stack :**
* Symfony 4.1.6
* swarrot/swarrot-bundle : v1.5.1
* RabbitMQ Server : 3.7
* HaProxy 1.7
* Using the default "pecl" provider/factory

**Our problem**
1. Our HaProxy has a timeout that close the connection between our application and RabbitMQ.
2. According to RabbitMQ specs, the use of heartbeats is highly recommended (https://www.rabbitmq.com/heartbeats.html)
3. Do you know any implementation to manage heartbeats using the PECL provider with the SwarrotBundle ?

Thanks

**Comment by dorianyah** [comment]
Hi,

Thanks for the fast feedback.

**Answers to your 3 questions :**

1. Here is the essential part of our HaProxy configuration, we are using timeout of 10 seconds
```  
defaults
  timeout connect 10s
  timeout client 10s
  timeout server 10s
```
2. We are experiencing that while publishing. We are using a daemon that publish messages on a irregular basis.
But because the connection is established once at the first "publishing", it is closed when no messages are sent for more than the "10s defined timeout". We then noticed a crash of the script with this exception :
"[Error] Library error: a socket error occured"
"[Error] Could not publish to exchange. No channel available"

3. We understood that sending heartbeats could maintain a TCP connection opened during a certain amount of time to keep some TCP activity and to prevent the connexion to be closed by a proxy.

We first thought of implementing a reconnection pattern, but as the heartbeat seems to be a core feature of the AMQP protocol, we were interested in using it.

Thanks for any insight

**Comment by odolbeau** [comment]
Thanks, that's perfectly clear!

As mention in the documentation I gave previously, I doubt you'll solve your problem with the heartbeat implementation provided by the pecl extension.
Anyway, don't hesitate to make a PR to support this option in the bundle. You should only need to update the `PeclFactory` to update your connection if a heartbeat is specified (in the url maybe?).

2 others solutions you should consider:
* Increase timeouts in your HA configuration for your RMQ backend.
* Ensure the connection is correctly established (See: [AMQPChannel::isConnected()](https://github.com/pdezwart/php-amqp/blob/master/stubs/AMQPChannel.php#L35-L42) & [AMQPConnection::reconnect()](https://github.com/pdezwart/php-amqp/blob/master/stubs/AMQPConnection.php#L155-L162))

**Comment by dorianyah** [comment]
Thanks, we will investigate this.

We also found that the swarrot bundle can be used with amqp_lib as a provider.
But while trying to install it with any version X.Y (tried : 2.1, 2.8...)
```
composer require php-amqplib/php-amqplib "X.Y"
```
we get the following error (even with minimum-stability set to dev):
```
[InvalidArgumentException]                                                                                                                                                                               
  Could not find a matching version of package php-amqplib/php-amqplib. Check the package spelling, your version constraint and that the package is available in a stability which matches your minimum-s  
  tability (stable).
```
Do you happen to have any experience or tips in installing amqp_lib with the Bundle ?
Thanks
