### ISSUE TITLE
Symfony 4.3 deprecations

### ISSUE THREAD

**Issue by pvgnd** [swarrot/SwarrotBundle#159]
As of Symfony 4.3, the SwarrotBundle generates deprecation notices :

> The "Swarrot\SwarrotBundle\Event\MessagePublishedEvent" class extends "Symfony\Component\EventDispatcher\Event" that is deprecated since Symfony 4.3, use "Symfony\Contracts\EventDispatcher\Event" instead.

> Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.

**Comment by monsieurchico** [comment]
up ?

**Comment by odolbeau** [comment]
> up ?

Hi @monsieurchico 
I saw this issue, don't worry, you don't need to ping me another time with such a (useless) message, furthermore 10 days before the issue have been created.

Please keep in mind this is an open source project. Which means:
- I'm not paid to maintain it
- I'm not working on it on a daily basis
- **You can contribute yourself by proposing a PR** (This is highly appreciated! <3)

If you're interested by contributing, take a look at [this interface](https://github.com/symfony/event-dispatcher-contracts/blob/master/EventDispatcherInterface.php) to find some inspiration. :)

**Comment by pvgnd** [comment]
Hello @odolbeau,

How do you want to handle this change as the event name published will introduce a breaking change ?

- Update composer.json to mark the bundle requirements to symfony >= 4.3 ?
- Manage a backward compatibility layer to stay compatible with symfony < 4.3 ? Any idea for that ?
