### ISSUE TITLE
Reset application after each consummed message

### ISSUE THREAD

**Issue by pvgnd** [swarrot/SwarrotBundle#170]
As of Symfony 4.4, we can reset application (`$this->getApplication()->reset();`) in a Symfony Command.  

This is usefull to reset Monolog (when finger crossed is used for example), and free resources while waiting for messages.

**Comment by odolbeau** [comment]
Hi @pvgnd 
It an excellent idea & @lyrixx suggested it too https://github.com/swarrot/swarrot/issues/193

Don't hesitate to propose an implementation. :)
