### ISSUE TITLE
Allow users to attach aliases to Swarrot commands

### ISSUE THREAD

**Issue by pierrelemee** [swarrot/SwarrotBundle#186]
# Allow users to attach aliases to Swarrot commands

As a user of the Swarrot consumption `command`, I'd like to be allowed to use _my_ command name.

In practice, it's probably more intuitive to refer to a command name `my:custom:action` than `swarrot:consume:my_custom_action`.

Considering that since SF3.2, [command aliases are supported](https://symfony.com/blog/new-in-symfony-3-2-console-improvements-part-1),  it would be great to allow users to define their aliases on top of current Swarrot configuration

**Comment by odolbeau** [comment]
Good idea! :+1:

**Comment by odolbeau** [comment]
Fixed by #192
