### ISSUE TITLE
Consumer on multiple queues

### ISSUE THREAD

**Issue by TakTaki** [swarrot/SwarrotBundle#201]
Hi,
I'm trying to make one of my consumer consume multiple queues but I can't find the command nor the configuration to do so.
Is it possible ?

Thanks

**Comment by odolbeau** [comment]
Hi @TakTaki!
No, it's not possible to consume multiple queues with the same worker instance.

**Comment by TakTaki** [comment]
Thanks for the reply.
So, what to you mean when you said https://github.com/swarrot/SwarrotBundle/issues/32#issuecomment-58623873 ? 
Is this juste a common behavior that Swarrot doesn't handle ?

**Comment by odolbeau** [comment]
You can launch a worker using `bin/console swarrot:consume:my_consumer queue_name [connection_name]`
1 worker instance can consume 1 queue but you can launch several workers in parallel:
```
bin/console swarrot:consume:my_consumer queue_1
bin/console swarrot:consume:my_consumer queue_2
bin/console swarrot:consume:my_consumer queue_3
```
You will have 2 distinct workers, each consuming a different queue.
