### ISSUE TITLE
Non-existed services

### ISSUE THREAD

**Issue by serhiiosm** [swarrot/SwarrotBundle#225]
bin/console swarrot:consume:account.create account_created accounts --env=prod

In App_KernelProdContainer.php line 1976:
                                                                                                                  
  Attempted to load class "RpcServerProcessorConfigurator" from namespace "Swarrot\SwarrotBundle\Processor\RPC".  
  Did you forget a "use" statement for another namespace?   

[https://github.com/swarrot/SwarrotBundle/pull/224](PR)

**Comment by metfan** [comment]
https://github.com/swarrot/SwarrotBundle/pull/231
