### ISSUE TITLE
what is the goal of extras in the messages_types config

### ISSUE THREAD

**Issue by stof** [swarrot/SwarrotBundle#44]
The `messages_types` feature is missing some documentation. For instance, the config defines an array `extras`, but I cannot find where it is used

**Comment by odolbeau** [comment]
It's used to configure some options in the `SwarrotCommand`. It's definitively not very useful except if you define your own default SwarrotCommand and if you need to change the behavior.

For example, we have 3 commands to consume messages. `default`, `aws` & `payment`. Each of them can have different retry strategies based on the `extras` configuration key.

You're right, the documentation (& tests) definitively need some love. :/

**Comment by stof** [comment]
Should this array be considered as a map or as a sequence ? The current configuration tree considers it as a sequence, which means keys are lost in case multiple files need to be merged (there is a bug in Symfony which does not reset the keys in case no merging is necessary)
