### ISSUE TITLE
Support configuring the connection with a URL

### ISSUE THREAD

**Issue by stof** [swarrot/SwarrotBundle#50]
On Paas platforms like Heroku, it is common for addons to expose their credentials as an URL (`amqp://login:password@host:post/vhost` in the case of RabbitMQ). In my project, I currently rely on `prependExtensionConfiguration` in my own DI extension to parse the URL into the format of the bundle. What do you think about supporting the url-based configuration in the bundle directly ?

**Comment by odolbeau** [comment]
No problem with that. :)

**Comment by stof** [comment]
I will send a PR soon adapting the logic I have in my project

**Comment by odolbeau** [comment]
Fixed by #124
