### ISSUE TITLE
The ObjectManagerProcessor is added at the wrong place in the stack

### ISSUE THREAD

**Issue by stof** [swarrot/SwarrotBundle#53]
Currently, the object manager is not reset or cleared when an exception happens in the processing, because the logic is not reached. This makes it partially useless given that the entityManager generally happens because of an exception (it is always the case, unless you close it yourself for a weird reason. Doctrine only closes itself on exceptions).
The ObjectManagerProcessor should be added in the stack outside the ExceptionCatcherProcessor, not inside it.

**Comment by odolbeau** [comment]
Yes, it seems right. Is it OK for you @gignonje ?

**Comment by gignonje** [comment]
Indeed, you are right. Sorry about that mistake.
