### ISSUE TITLE
Add extension point to provider

### ISSUE THREAD

**Issue by jderusse** [swarrot/SwarrotBundle#66]
By defining services directly in the extension, it's very hard to add a our own provider.
It could be easier with:
 - moving the logic in a compiler pass
 - using a provider_service instead of a provider key

**Comment by Taluu** [comment]
I already tried to push using compiler passes (see #2), but it didn't look useful at the time. I'm +1 for that if this though can be revised though.

**Comment by jderusse** [comment]
Oh, I didn't check previous PR. 
IMHO: yours was nicest (alias not compulsory, cleanup temporary parameters, ...).

@odolbeau do you change your mind about intergating such PR? 
Actualy to add a custom provider, I have to use a CompilerPass to change the class and arguments of `swarrot.factory.pecl` it's ugly but it works...

**Comment by Taluu** [comment]
That was way before some refactos happened on the Bundle I think though, so my pr would need to be started from scratch though :/

**Comment by jderusse** [comment]
OK then, I update my PR #67 .
I didn't take the `comandPass` wich could be done in another PR.
