### ISSUE TITLE
SVG version of the logo

### ISSUE THREAD

**Issue by stof** [swarrot/SwarrotBundle#68]
The profiler integration should be updated to the new design
The way to do it has not yet been documented, but I can work on it (I know how it works as I worked on the system allowing bundles to support both 2.7 and 2.8 properly).
However, the new profiler expects icons to be defined in SVG (2.7 already uses SVG rather than PNG btw, making the profiler retina-ready, but it still allowed to use both).

Do you have an SVG version of the logo ?

**Comment by odolbeau** [comment]
I don't have any svg version as it's a random image I found on Google... :/

**Comment by stof** [comment]
maybe it's time to create a real logo for Swarrot :smile:

**Comment by stof** [comment]
@odolbeau you told me you got a new logo when we met. It would be great to make it available somewhere (and also the grey version of it as it is what I need for the profiler to fit in the toolbar design)

**Comment by odolbeau** [comment]
Finally, here it is! \o/
https://www.dropbox.com/s/9ar8qsalb80zejr/Logo%20Swarrot%20no%20text.svg?dl=0

**Comment by stof** [comment]
@odolbeau Can you ask for a grayscale version for usage in the toolbar ?

**Comment by stof** [comment]
btw, instead of keeping it in dropdown, I suggest creating a ``swarrot/assets`` repository to store the logos

**Comment by stof** [comment]
@odolbeau any news about a grayscale version of the logo ?

**Comment by odolbeau** [comment]
I put all available assets in a dedicated repository: https://github.com/swarrot/assets

I'll see tomorrow to have a SVG greyscale logo! :)

**Comment by odolbeau** [comment]
Here it is: https://github.com/swarrot/assets/blob/master/logo-bw-no-text_140x140.svg

**Comment by stof** [comment]
great. We can now start the work about supporting the webprofiler design v2, for better integration with Symfony 2.8+

**Comment by stof** [comment]
Closing this issue as the SVG logo is available since a long time. I opened #140 to track the upgrade of the profiler panel (which was totally forgotten during these 2 years)
